version: '3.8'

services:
  mysql:
    image: mysql:8.0.23
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 33067:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6380:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=localhost:redis:6379
    ports:
      - '8082:8081'
    depends_on:
      - redis
