import { BasketItem } from './basket-item.entity';

export class Basket {
  id: string; // uuid, generated by client

  items: BasketItem[];

  deliveryMethodId?: string;

  clientSecret: string;

  paymentIntentId: string;

  constructor(id: string) {
    this.id = id;
    this.items = [];
  }
}
